#file containing main control flow and simulation code


#import math
from modelDef import OverallModel
import csv

# PREPARING the list of agent params to be instantiated in model by reading in the CSVs
#CSVs are generated by modifying the excel file's sheets and exporting them.

with open("FixNodes1.csv") as f:
    FnList = []
    reader = csv.reader(f, delimiter = ",")
    for item in reader:
        FnList.append(item)
        #print(item)
    FnList.pop(0)

#print(FnList)


with open("VarNodes3.csv") as f1:
    VnList = []
    reader1 = csv.reader(f1, delimiter = ",")
    for item1 in reader1:
        VnList.append(item1)
        #print("Test =")
        #print(item)
    VnList.pop(0)
#print("This should be VnList:  \n")
#print(VnList)
#print("\n")

with open("Transporters2.csv") as f2:
    TList = []
    reader2 = csv.reader(f2, delimiter = ",")
    for item2 in reader2:
        TList.append(item2)
        #print(item)
    TList.pop(0)


#ACTUAL MODEL SETUP
new_model = OverallModel(FnList,VnList,TList)

simDur =  30 * 24 * 60 * 60 #number of seconds to run sim for
dts = int(simDur/new_model.time_step)
print("Beginning Simulation")
for i in range(0,dts):
    #print("Current Time: +"+str(i))
    new_model.step()
print("Simulation Complete")
new_model.close_model()